services:
  dns_server:
    build:
      context: ./dns_server
      dockerfile: Dockerfile
    networks:
      - network
      - p2p
    #this for running first database and then dns server
    depends_on:
      - database
    #setting an environment variable in the container
    environment:
      - DATABASE_URL=sqlite:///data/dns.db

  client_1:
    build:
      context: ./client_1
      dockerfile: Dockerfile
    networks:
      - network
    depends_on:
      - dns_server

  client_2:
    build:
      context: ./client_2
      dockerfile: Dockerfile
    networks:
      - network
    depends_on:
      - dns_server
  
  database:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data:/data
    networks:
      - p2p
  
networks:
  network:
  p2p:
