services:
  dns_server:
    build:
      context: ./dns_server
      dockerfile: Dockerfile
    networks:
      - network
    depends_on:
      - mysql_database
    environment:
      - DATABASE_URL=mysql://root:password@mysql_database:3306/DNS

  client_1:
    build:
      context: ./client_1
      dockerfile: Dockerfile
    networks:
      - network
    depends_on:
      - dns_server

  client_2:
    build:
      context: ./client_2
      dockerfile: Dockerfile
    networks:
      - network
    depends_on:
      - dns_server

  mysql_database:
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - network
    ports:
      - "3306:3306"

networks:
  network:
