version: '3.8'

services:
  dns_server:
    build:
      context: ./dns_server
      dockerfile: Dockerfile
    networks:
      - network

  client_1:
    build:
      context: ./client_1
      dockerfile: Dockerfile
    networks:
      - network

  client_2:
    build:
      context: ./client_2
      dockerfile: Dockerfile
    networks:
      - network
  
networks:
  network:
